// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchAds():Promise<Array<string>>;

export function FetchSettings():Promise<main.SettingsResult>;

export function LookupBarcode(arg1:string):Promise<main.BeverageResult>;

export function RandomBeverage():Promise<main.BeverageResult>;

export function ReportBeverage(arg1:string,arg2:string):Promise<boolean>;
