// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchAds() {
  return window['go']['main']['App']['FetchAds']();
}

export function LookupBarcode(arg1) {
  return window['go']['main']['App']['LookupBarcode'](arg1);
}

export function RandomBeverage() {
  return window['go']['main']['App']['RandomBeverage']();
}
